### ISSUE TITLE
Latest build, doesn't. Crashes looking for non-existent PCM devices

### ISSUE THREAD

**Issue by desrod** [chuot/rc-scanner#37]
As below: 

```
master /tmp/rc-scanner $ DEBUG=true node run.js 
Building client app...
> rc-scanner-client@0.10.3 build
> ng build --base-href ./ --configuration production

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.
✔ Service worker generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.744010dbd4a1885a.js      | main          | 274.33 kB |                68.04 kB
styles.bffbb93370ba1ac9.css   | styles        |  72.42 kB |                 7.48 kB
polyfills.4a84457d02bc33fa.js | polyfills     |  44.50 kB |                13.54 kB
runtime.499407861cd0ca2a.js   | runtime       |   1.05 kB |               600 bytes

                              | Initial Total | 392.29 kB |                89.65 kB

Build at: 2022-12-31T02:03:21.891Z - Hash: ff6dc5cf8fd2c8b5 - Time: 2700ms
 done
ALSA lib pcm_direct.c:2127:(_snd_pcm_direct_new) unable to create IPC semaphore
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_bluetooth.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_bluetooth.so: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_bluetooth.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_bluetooth.so: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_a2dpd.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_a2dpd.so: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_a2dpd.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_a2dpd.so: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_sco.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_sco.so: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_sco.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_sco.so: cannot open shared object file: No such file or directory)
PortAudio V19.6.0-devel, revision unknown
Input audio options: default device, sample rate 44100, channels 1, bits per sample 16, max queue 2, frames per buffer 0, close on error false
Input device name is default
file:///tmp/rc-scanner/server/lib/rc-scanner/com.js:31
        this.readLine = new SerialPort.parsers.Readline({ delimiter: '\r', encoding: 'binary' });
                                               ^

TypeError: Cannot read properties of undefined (reading 'Readline')
    at new Com (file:///tmp/rc-scanner/server/lib/rc-scanner/com.js:31:48)
    at new RcScanner (file:///tmp/rc-scanner/server/lib/rc-scanner/main.js:59:20)
    at new App (file:///tmp/rc-scanner/server/index.js:149:26)
    at file:///tmp/rc-scanner/server/index.js:183:20
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1


An error has occured. Please re-run the command like this: 'DEBUG=true node run.js'
```

This is with the latest npm/node LTS (18.12.1-deb-1nodesource1) running on Ubuntu 22.04.

**Comment by chuot** [comment]
Have you updated the node packages? The code works with the serialport version 9 package. It looks like serialport v10 has some breaking changes.
